#!/bin/bash



MHWD_ADD_DEVICE_SECTION()
{
	echo 'Section "Device"' >> "$2"
	echo '	Identifier  "Device0"' >> "$2"
	echo "	Driver      \"$1\"" >> "$2"
	echo 'EndSection' >> "$2"
	echo ' ' >> "$2"
}


MHWD_ADD_DRI()
{
	# only for free drivers
	sed -i /'Section "Device"'/,/'EndSection'/s/'EndSection'/"\tOption      \"DRI\"    \"true\"\nEndSection"/g "$1"

	echo ' ' >> "$1"
	echo 'Section "DRI"' >> "$1"
	echo '        Group  "video"' >> "$1"
	echo '        Mode   0666' >> "$1"
	echo 'EndSection' >> "$1"
	echo ' ' >> "$1"
}


MHWD_ADD_COMPOSITING()
{
	echo ' ' >> "$1"
	echo 'Section "Extensions"' >> "$1"
	echo '	Option "Composite" "Enable"' >> "$1"
	echo '	Option "RENDER"    "Enable"' >> "$1"
	echo 'EndSection' >> "$1"
	echo ' ' >> "$1"
}


MHWD_ADD_BACKSPACE()
{
	echo ' ' >> "$1"
	echo 'Section "InputClass"' >> "$1"
	echo '	Identifier          "Keyboard Defaults"' >> "$1"
	echo '	MatchIsKeyboard	    "yes"' >> "$1"
	echo '	Option              "XkbOptions" "terminate:ctrl_alt_bksp"' >> "$1"
	echo 'EndSection' >> "$1"
	echo ' ' >> "$1"
}


# Make them readonly
declare -fr MHWD_ADD_DEVICE_SECTION MHWD_ADD_DRI MHWD_ADD_COMPOSITING MHWD_ADD_BACKSPACE

