#!/bin/bash 

NOTLOADEDMODULES=""

eval $(hwdetect --modules)
 for m in ${MODULES[*]}; do
   if ! grep -sq $(echo $m|tr - _) <(lsmod); then
     NOTLOADEDMODULES+="${m}|"
   fi
 done

echo "${NOTLOADEDMODULES}"
