#!/bin/bash

build() {
    # Add KMS modules
    add_module "radeon"
    add_module "nouveau"
    add_module "i915"
    add_module "via-agp"
    add_module "sis-agp"
    add_module "intel-agp"

    if [[ $(uname -m) == i686 ]]; then
        add_module "amd64-agp"
        add_module "ati-agp"
        add_module "sworks-agp"
        add_module "ali-agp"
        add_module "amd-k7-agp"
        add_module "nvidia-agp"
        add_module "efficeon-agp"
    fi

    # Add uvesafb
    add_module 'uvesafb'
    add_binary "v86d"
    add_file "/usr/lib/modprobe.d/uvesafb.conf"
    add_dir "/etc/modprobe.d"

    add_runscript
}

help() {
    echo "This hook sets up the right framebuffer on boot."
}

# vim: set ft=sh ts=4 sw=4 expandtab:
